# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  #name: cluster-dave
  name: cluster2
  region: us-west-1

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 3